### ISSUE TITLE
Fans at maximum during lockscreen

### ISSUE THREAD

**Issue by welcoMattic** [jeffmhubbard/multilockscreen#25]
I installed multillockscreen 2 days ago, and my fans are at the maximum each time I lock my computer, during all locking time.

My config:
ArchLinux
i3
LightDM

If you need more info, tell me :)

**Comment by jeffmhubbard** [comment]
There's nothing CPU intensive happening during `--lock`, so that's kinda strange. Does the same thing happen if you call i3lock by itself: `i3lock -i image.png`?

Please post the command you are running and your config file if you're using one.

**Comment by welcoMattic** [comment]
I run `multilockscreen -l --display 2 --span` from a keyboard shortcut
Config:
``` 
 # default options
 display_on=0
 span_image=false
 lock_timeout=300
 fx_list=(dim blur dimblur pixel dimpixel color)
 dim_level=40
 blur_level=1
 pixel_scale=10,1000
 solid_color=333333
 # theme options
 loginbox=00000066
 loginshadow=00000000
 locktext="Type password to unlock..."
 font="sans-serif"
 ringcolor=ffffffff
 insidecolor=00000000
 separatorcolor=00000000
 ringvercolor=ffffffff
 insidevercolor=00000000
 ringwrongcolor=ffffffff
 insidewrongcolor=980000ff
 keyhlcolor=980000ff
 bshlcolor=980000ff
 verifcolor=ffffffff
 timecolor=ffffffff
 datecolor=ffffffff
```

If I run only `i3lock -i /path/to/my-image.png` by itself it doesn't start fans.

**Comment by jeffmhubbard** [comment]
I can't duplicate the issue, so I'm not really sure. Does this only happen using the keyboard shortcut? How about just `multilockscreen --lock` from a terminal?

I found i3/i3lock#141, which sounds like what you're experiencing. Killing compton (or picom) seemed to help, so that may worth investigating.

Beyond that, I'd suggest switching to the console while this is happening. Use `top` or `ps` to see what processes might be causing problems.

**Comment by welcoMattic** [comment]
I will take a look on this soon. It could be `picom` related, thanks for the advice.
