### ISSUE TITLE
DPMS re-enabled despite being disabled pre-lock

### ISSUE THREAD

**Issue by Vel1khan** [jeffmhubbard/multilockscreen#37]
(Arch kernel 5.9.2-arch1-1)
As per the title, after doing `multilockscreen -l`, DPMS becomes re-enabled. I explicitly used `xset -dpms` and checked with `xset -q` to make sure that it was disabled before. In the config, I have made sure `lock_timeout=0`(changing this value has no effect on this issue anyway it seems) . i3lock and i3lock-color do not exhibit this behaviour. Neither does locking with gtk-greeter. I am not sure whether this is an issue inherited from betterlockscreen, however the conditional that disables DPMS (line 143) seems to not run.

I would try to submit a PR but I am stumped as to how to solve this. From my own testing, it appears that $DEFAULT_DPMS is parsed correctly and contains the correct string "Enabled"/"Disabled". I tested it with this:

```
#!/usr/bin/env bash
DEFAULT_DPMS=$(xset q | awk '/^[[:blank:]]*DPMS is/ {print $(NF)}')

if [ "$DEFAULT_DPMS" = "Disabled" ]; then
echo "Pass"
else
echo "Fail"
fi
```
I am therefore very confused as to why it does not work. I suspect the variable gets emptied/changed somehow after unlocking?
Could you please try to replicate this and check if it can be fixed?

**Comment by jeffmhubbard** [comment]
The problem is\was that `lock_timeout` is explicitly set so `[ -n $lock_timeout ]` always passes. Setting to `0` would just make the screen blank immediately. Even if the user has disabled DPMS (`xset -dpms`), it was being enabled in `prelock()` and disabled in `postlock()`. I still don't know why it wasn't being disabled for you.

I think the better approach is to only make changes to DPMS settings if DPMS is already enabled. #37 should fix this.

**Comment by Vel1khan** [comment]
Just tested it, works perfectly, DPMS is no longer being re-enabled!
